package net.minecraft.stat;

import net.minecraft.util.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.entity.EntityType;
import net.minecraft.item.Item;
import net.minecraft.block.Block;

public class Stats
{
    public static final StatType<Block> a;
    public static final StatType<Item> b;
    public static final StatType<Item> c;
    public static final StatType<Item> d;
    public static final StatType<Item> e;
    public static final StatType<Item> f;
    public static final StatType<EntityType<?>> g;
    public static final StatType<EntityType<?>> h;
    public static final StatType<Identifier> i;
    public static final Identifier j;
    public static final Identifier k;
    public static final Identifier l;
    public static final Identifier m;
    public static final Identifier n;
    public static final Identifier o;
    public static final Identifier p;
    public static final Identifier q;
    public static final Identifier r;
    public static final Identifier s;
    public static final Identifier t;
    public static final Identifier u;
    public static final Identifier v;
    public static final Identifier w;
    public static final Identifier x;
    public static final Identifier y;
    public static final Identifier z;
    public static final Identifier A;
    public static final Identifier B;
    public static final Identifier C;
    public static final Identifier D;
    public static final Identifier E;
    public static final Identifier F;
    public static final Identifier G;
    public static final Identifier H;
    public static final Identifier I;
    public static final Identifier J;
    public static final Identifier K;
    public static final Identifier L;
    public static final Identifier M;
    public static final Identifier N;
    public static final Identifier O;
    public static final Identifier P;
    public static final Identifier Q;
    public static final Identifier R;
    public static final Identifier S;
    public static final Identifier T;
    public static final Identifier U;
    public static final Identifier V;
    public static final Identifier W;
    public static final Identifier X;
    public static final Identifier Y;
    public static final Identifier Z;
    public static final Identifier aa;
    public static final Identifier ab;
    public static final Identifier ac;
    public static final Identifier ad;
    public static final Identifier ae;
    public static final Identifier af;
    public static final Identifier ag;
    public static final Identifier ah;
    public static final Identifier ai;
    public static final Identifier aj;
    public static final Identifier ak;
    public static final Identifier al;
    public static final Identifier am;
    public static final Identifier an;
    public static final Identifier ao;
    public static final Identifier ap;
    public static final Identifier aq;
    public static final Identifier ar;
    public static final Identifier as;
    public static final Identifier at;
    public static final Identifier au;
    public static final Identifier av;
    public static final Identifier aw;
    public static final Identifier ax;
    public static final Identifier ay;
    public static final Identifier az;
    
    private static Identifier register(final String string, final StatFormatter statFormatter) {
        final Identifier identifier3 = new Identifier(string);
        Registry.<Identifier>register(Registry.CUSTOM_STAT, string, identifier3);
        Stats.i.getOrCreateStat(identifier3, statFormatter);
        return identifier3;
    }
    
    private static <T> StatType<T> registerType(final String string, final Registry<T> registry) {
        return Registry.<StatType<T>>register(Registry.STAT_TYPE, string, new StatType<T>(registry));
    }
    
    static {
        a = Stats.<Block>registerType("mined", Registry.BLOCK);
        b = Stats.<Item>registerType("crafted", Registry.ITEM);
        c = Stats.<Item>registerType("used", Registry.ITEM);
        d = Stats.<Item>registerType("broken", Registry.ITEM);
        e = Stats.<Item>registerType("picked_up", Registry.ITEM);
        f = Stats.<Item>registerType("dropped", Registry.ITEM);
        g = Stats.<EntityType<?>>registerType("killed", Registry.ENTITY_TYPE);
        h = Stats.<EntityType<?>>registerType("killed_by", Registry.ENTITY_TYPE);
        i = Stats.<Identifier>registerType("custom", Registry.CUSTOM_STAT);
        j = register("leave_game", StatFormatter.DEFAULT);
        k = register("play_one_minute", StatFormatter.TIME);
        l = register("time_since_death", StatFormatter.TIME);
        m = register("time_since_rest", StatFormatter.TIME);
        n = register("sneak_time", StatFormatter.TIME);
        o = register("walk_one_cm", StatFormatter.DISTANCE);
        p = register("crouch_one_cm", StatFormatter.DISTANCE);
        q = register("sprint_one_cm", StatFormatter.DISTANCE);
        r = register("walk_on_water_one_cm", StatFormatter.DISTANCE);
        s = register("fall_one_cm", StatFormatter.DISTANCE);
        t = register("climb_one_cm", StatFormatter.DISTANCE);
        u = register("fly_one_cm", StatFormatter.DISTANCE);
        v = register("walk_under_water_one_cm", StatFormatter.DISTANCE);
        w = register("minecart_one_cm", StatFormatter.DISTANCE);
        x = register("boat_one_cm", StatFormatter.DISTANCE);
        y = register("pig_one_cm", StatFormatter.DISTANCE);
        z = register("horse_one_cm", StatFormatter.DISTANCE);
        A = register("aviate_one_cm", StatFormatter.DISTANCE);
        B = register("swim_one_cm", StatFormatter.DISTANCE);
        C = register("jump", StatFormatter.DEFAULT);
        D = register("drop", StatFormatter.DEFAULT);
        E = register("damage_dealt", StatFormatter.DIVIDE_BY_TEN);
        F = register("damage_dealt_absorbed", StatFormatter.DIVIDE_BY_TEN);
        G = register("damage_dealt_resisted", StatFormatter.DIVIDE_BY_TEN);
        H = register("damage_taken", StatFormatter.DIVIDE_BY_TEN);
        I = register("damage_blocked_by_shield", StatFormatter.DIVIDE_BY_TEN);
        J = register("damage_absorbed", StatFormatter.DIVIDE_BY_TEN);
        K = register("damage_resisted", StatFormatter.DIVIDE_BY_TEN);
        L = register("deaths", StatFormatter.DEFAULT);
        M = register("mob_kills", StatFormatter.DEFAULT);
        N = register("animals_bred", StatFormatter.DEFAULT);
        O = register("player_kills", StatFormatter.DEFAULT);
        P = register("fish_caught", StatFormatter.DEFAULT);
        Q = register("talked_to_villager", StatFormatter.DEFAULT);
        R = register("traded_with_villager", StatFormatter.DEFAULT);
        S = register("eat_cake_slice", StatFormatter.DEFAULT);
        T = register("fill_cauldron", StatFormatter.DEFAULT);
        U = register("use_cauldron", StatFormatter.DEFAULT);
        V = register("clean_armor", StatFormatter.DEFAULT);
        W = register("clean_banner", StatFormatter.DEFAULT);
        X = register("clean_shulker_box", StatFormatter.DEFAULT);
        Y = register("interact_with_brewingstand", StatFormatter.DEFAULT);
        Z = register("interact_with_beacon", StatFormatter.DEFAULT);
        aa = register("inspect_dropper", StatFormatter.DEFAULT);
        ab = register("inspect_hopper", StatFormatter.DEFAULT);
        ac = register("inspect_dispenser", StatFormatter.DEFAULT);
        ad = register("play_noteblock", StatFormatter.DEFAULT);
        ae = register("tune_noteblock", StatFormatter.DEFAULT);
        af = register("pot_flower", StatFormatter.DEFAULT);
        ag = register("trigger_trapped_chest", StatFormatter.DEFAULT);
        ah = register("open_enderchest", StatFormatter.DEFAULT);
        ai = register("enchant_item", StatFormatter.DEFAULT);
        aj = register("play_record", StatFormatter.DEFAULT);
        ak = register("interact_with_furnace", StatFormatter.DEFAULT);
        al = register("interact_with_crafting_table", StatFormatter.DEFAULT);
        am = register("open_chest", StatFormatter.DEFAULT);
        an = register("sleep_in_bed", StatFormatter.DEFAULT);
        ao = register("open_shulker_box", StatFormatter.DEFAULT);
        ap = register("open_barrel", StatFormatter.DEFAULT);
        aq = register("interact_with_blast_furnace", StatFormatter.DEFAULT);
        ar = register("interact_with_smoker", StatFormatter.DEFAULT);
        as = register("interact_with_lectern", StatFormatter.DEFAULT);
        at = register("interact_with_campfire", StatFormatter.DEFAULT);
        au = register("interact_with_cartography_table", StatFormatter.DEFAULT);
        av = register("interact_with_loom", StatFormatter.DEFAULT);
        aw = register("interact_with_stonecutter", StatFormatter.DEFAULT);
        ax = register("bell_ring", StatFormatter.DEFAULT);
        ay = register("raid_trigger", StatFormatter.DEFAULT);
        az = register("raid_win", StatFormatter.DEFAULT);
    }
}
