package net.minecraft.state.property;

import java.util.function.Predicate;
import net.minecraft.block.enums.BambooLeaves;
import net.minecraft.block.enums.StructureBlockMode;
import net.minecraft.block.enums.StairShape;
import net.minecraft.block.enums.SlabType;
import net.minecraft.block.enums.PistonType;
import net.minecraft.block.enums.Instrument;
import net.minecraft.block.enums.DoorHinge;
import net.minecraft.block.enums.ComparatorMode;
import net.minecraft.block.enums.ChestType;
import net.minecraft.block.enums.BedPart;
import net.minecraft.block.enums.RailShape;
import net.minecraft.block.enums.BlockHalf;
import net.minecraft.block.enums.DoubleBlockHalf;
import net.minecraft.block.enums.WireConnection;
import net.minecraft.block.enums.Attachment;
import net.minecraft.block.enums.WallMountLocation;
import net.minecraft.util.math.Direction;

public class Properties
{
    public static final BooleanProperty ATTACHED;
    public static final BooleanProperty BOTTOM;
    public static final BooleanProperty CONDITIONAL;
    public static final BooleanProperty DISARMED;
    public static final BooleanProperty DRAG;
    public static final BooleanProperty ENABLED;
    public static final BooleanProperty EXTENDED;
    public static final BooleanProperty EYE;
    public static final BooleanProperty FALLING;
    public static final BooleanProperty HANGING;
    public static final BooleanProperty HAS_BOTTLE_0;
    public static final BooleanProperty HAS_BOTTLE_1;
    public static final BooleanProperty HAS_BOTTLE_2;
    public static final BooleanProperty HAS_RECORD;
    public static final BooleanProperty HAS_BOOK;
    public static final BooleanProperty INVERTED;
    public static final BooleanProperty IN_WALL;
    public static final BooleanProperty LIT;
    public static final BooleanProperty LOCKED;
    public static final BooleanProperty OCCUPIED;
    public static final BooleanProperty OPEN;
    public static final BooleanProperty PERSISTENT;
    public static final BooleanProperty POWERED;
    public static final BooleanProperty SHORT;
    public static final BooleanProperty SIGNAL_FIRE;
    public static final BooleanProperty SNOWY;
    public static final BooleanProperty TRIGGERED;
    public static final BooleanProperty UNSTABLE;
    public static final BooleanProperty WATERLOGGED;
    public static final EnumProperty<Direction.Axis> AXIS_XZ;
    public static final EnumProperty<Direction.Axis> AXIS_XYZ;
    public static final BooleanProperty UP_BOOL;
    public static final BooleanProperty DOWN_BOOL;
    public static final BooleanProperty NORTH_BOOL;
    public static final BooleanProperty EAST_BOOL;
    public static final BooleanProperty SOUTH_BOOL;
    public static final BooleanProperty WEST_BOOL;
    public static final DirectionProperty FACING;
    public static final DirectionProperty HOPPER_FACING;
    public static final DirectionProperty FACING_HORIZONTAL;
    public static final EnumProperty<WallMountLocation> WALL_MOUNT_LOCATION;
    public static final EnumProperty<Attachment> ATTACHMENT;
    public static final EnumProperty<WireConnection> WIRE_CONNECTION_EAST;
    public static final EnumProperty<WireConnection> WIRE_CONNECTION_NORTH;
    public static final EnumProperty<WireConnection> WIRE_CONNECTION_SOUTH;
    public static final EnumProperty<WireConnection> WIRE_CONNECTION_WEST;
    public static final EnumProperty<DoubleBlockHalf> DOUBLE_BLOCK_HALF;
    public static final EnumProperty<BlockHalf> BLOCK_HALF;
    public static final EnumProperty<RailShape> RAIL_SHAPE;
    public static final EnumProperty<RailShape> STRAIGHT_RAIL_SHAPE;
    public static final IntegerProperty AGE_1;
    public static final IntegerProperty AGE_2;
    public static final IntegerProperty AGE_3;
    public static final IntegerProperty AGE_5;
    public static final IntegerProperty AGE_7;
    public static final IntegerProperty AGE_15;
    public static final IntegerProperty AGE_25;
    public static final IntegerProperty BITES;
    public static final IntegerProperty DELAY;
    public static final IntegerProperty DISTANCE_1_7;
    public static final IntegerProperty EGGS;
    public static final IntegerProperty HATCH;
    public static final IntegerProperty LAYERS;
    public static final IntegerProperty CAULDRON_LEVEL;
    public static final IntegerProperty COMPOSTER_LEVEL;
    public static final IntegerProperty FLUID_LEVEL;
    public static final IntegerProperty FLUID_BLOCK_LEVEL;
    public static final IntegerProperty MOISTURE;
    public static final IntegerProperty NOTE;
    public static final IntegerProperty PICKLES;
    public static final IntegerProperty POWER;
    public static final IntegerProperty SAPLING_STAGE;
    public static final IntegerProperty DISTANCE_0_7;
    public static final IntegerProperty ROTATION_16;
    public static final EnumProperty<BedPart> BED_PART;
    public static final EnumProperty<ChestType> CHEST_TYPE;
    public static final EnumProperty<ComparatorMode> COMPARATOR_MODE;
    public static final EnumProperty<DoorHinge> DOOR_HINGE;
    public static final EnumProperty<Instrument> INSTRUMENT;
    public static final EnumProperty<PistonType> PISTON_TYPE;
    public static final EnumProperty<SlabType> SLAB_TYPE;
    public static final EnumProperty<StairShape> STAIR_SHAPE;
    public static final EnumProperty<StructureBlockMode> STRUCTURE_BLOCK_MODE;
    public static final EnumProperty<BambooLeaves> BAMBOO_LEAVES;
    
    static {
        ATTACHED = BooleanProperty.create("attached");
        BOTTOM = BooleanProperty.create("bottom");
        CONDITIONAL = BooleanProperty.create("conditional");
        DISARMED = BooleanProperty.create("disarmed");
        DRAG = BooleanProperty.create("drag");
        ENABLED = BooleanProperty.create("enabled");
        EXTENDED = BooleanProperty.create("extended");
        EYE = BooleanProperty.create("eye");
        FALLING = BooleanProperty.create("falling");
        HANGING = BooleanProperty.create("hanging");
        HAS_BOTTLE_0 = BooleanProperty.create("has_bottle_0");
        HAS_BOTTLE_1 = BooleanProperty.create("has_bottle_1");
        HAS_BOTTLE_2 = BooleanProperty.create("has_bottle_2");
        HAS_RECORD = BooleanProperty.create("has_record");
        HAS_BOOK = BooleanProperty.create("has_book");
        INVERTED = BooleanProperty.create("inverted");
        IN_WALL = BooleanProperty.create("in_wall");
        LIT = BooleanProperty.create("lit");
        LOCKED = BooleanProperty.create("locked");
        OCCUPIED = BooleanProperty.create("occupied");
        OPEN = BooleanProperty.create("open");
        PERSISTENT = BooleanProperty.create("persistent");
        POWERED = BooleanProperty.create("powered");
        SHORT = BooleanProperty.create("short");
        SIGNAL_FIRE = BooleanProperty.create("signal_fire");
        SNOWY = BooleanProperty.create("snowy");
        TRIGGERED = BooleanProperty.create("triggered");
        UNSTABLE = BooleanProperty.create("unstable");
        WATERLOGGED = BooleanProperty.create("waterlogged");
        AXIS_XZ = EnumProperty.<Direction.Axis>create("axis", Direction.Axis.class, Direction.Axis.X, Direction.Axis.Z);
        AXIS_XYZ = EnumProperty.<Direction.Axis>create("axis", Direction.Axis.class);
        UP_BOOL = BooleanProperty.create("up");
        DOWN_BOOL = BooleanProperty.create("down");
        NORTH_BOOL = BooleanProperty.create("north");
        EAST_BOOL = BooleanProperty.create("east");
        SOUTH_BOOL = BooleanProperty.create("south");
        WEST_BOOL = BooleanProperty.create("west");
        FACING = DirectionProperty.create("facing", Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST, Direction.UP, Direction.DOWN);
        HOPPER_FACING = DirectionProperty.create("facing", direction -> direction != Direction.UP);
        FACING_HORIZONTAL = DirectionProperty.create("facing", Direction.Type.HORIZONTAL);
        WALL_MOUNT_LOCATION = EnumProperty.<WallMountLocation>create("face", WallMountLocation.class);
        ATTACHMENT = EnumProperty.<Attachment>create("attachment", Attachment.class);
        WIRE_CONNECTION_EAST = EnumProperty.<WireConnection>create("east", WireConnection.class);
        WIRE_CONNECTION_NORTH = EnumProperty.<WireConnection>create("north", WireConnection.class);
        WIRE_CONNECTION_SOUTH = EnumProperty.<WireConnection>create("south", WireConnection.class);
        WIRE_CONNECTION_WEST = EnumProperty.<WireConnection>create("west", WireConnection.class);
        DOUBLE_BLOCK_HALF = EnumProperty.<DoubleBlockHalf>create("half", DoubleBlockHalf.class);
        BLOCK_HALF = EnumProperty.<BlockHalf>create("half", BlockHalf.class);
        RAIL_SHAPE = EnumProperty.<RailShape>create("shape", RailShape.class);
        STRAIGHT_RAIL_SHAPE = EnumProperty.<RailShape>create("shape", RailShape.class, railShape -> railShape != RailShape.j && railShape != RailShape.i && railShape != RailShape.g && railShape != RailShape.h);
        AGE_1 = IntegerProperty.create("age", 0, 1);
        AGE_2 = IntegerProperty.create("age", 0, 2);
        AGE_3 = IntegerProperty.create("age", 0, 3);
        AGE_5 = IntegerProperty.create("age", 0, 5);
        AGE_7 = IntegerProperty.create("age", 0, 7);
        AGE_15 = IntegerProperty.create("age", 0, 15);
        AGE_25 = IntegerProperty.create("age", 0, 25);
        BITES = IntegerProperty.create("bites", 0, 6);
        DELAY = IntegerProperty.create("delay", 1, 4);
        DISTANCE_1_7 = IntegerProperty.create("distance", 1, 7);
        EGGS = IntegerProperty.create("eggs", 1, 4);
        HATCH = IntegerProperty.create("hatch", 0, 2);
        LAYERS = IntegerProperty.create("layers", 1, 8);
        CAULDRON_LEVEL = IntegerProperty.create("level", 0, 3);
        COMPOSTER_LEVEL = IntegerProperty.create("level", 0, 8);
        FLUID_LEVEL = IntegerProperty.create("level", 1, 8);
        FLUID_BLOCK_LEVEL = IntegerProperty.create("level", 0, 15);
        MOISTURE = IntegerProperty.create("moisture", 0, 7);
        NOTE = IntegerProperty.create("note", 0, 24);
        PICKLES = IntegerProperty.create("pickles", 1, 4);
        POWER = IntegerProperty.create("power", 0, 15);
        SAPLING_STAGE = IntegerProperty.create("stage", 0, 1);
        DISTANCE_0_7 = IntegerProperty.create("distance", 0, 7);
        ROTATION_16 = IntegerProperty.create("rotation", 0, 15);
        BED_PART = EnumProperty.<BedPart>create("part", BedPart.class);
        CHEST_TYPE = EnumProperty.<ChestType>create("type", ChestType.class);
        COMPARATOR_MODE = EnumProperty.<ComparatorMode>create("mode", ComparatorMode.class);
        DOOR_HINGE = EnumProperty.<DoorHinge>create("hinge", DoorHinge.class);
        INSTRUMENT = EnumProperty.<Instrument>create("instrument", Instrument.class);
        PISTON_TYPE = EnumProperty.<PistonType>create("type", PistonType.class);
        SLAB_TYPE = EnumProperty.<SlabType>create("type", SlabType.class);
        STAIR_SHAPE = EnumProperty.<StairShape>create("shape", StairShape.class);
        STRUCTURE_BLOCK_MODE = EnumProperty.<StructureBlockMode>create("mode", StructureBlockMode.class);
        BAMBOO_LEAVES = EnumProperty.<BambooLeaves>create("leaves", BambooLeaves.class);
    }
}
