package net.minecraft.sound;

import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class SoundEvents
{
    public static final SoundEvent a;
    public static final SoundEvent b;
    public static final SoundEvent c;
    public static final SoundEvent d;
    public static final SoundEvent e;
    public static final SoundEvent f;
    public static final SoundEvent g;
    public static final SoundEvent h;
    public static final SoundEvent i;
    public static final SoundEvent j;
    public static final SoundEvent k;
    public static final SoundEvent l;
    public static final SoundEvent m;
    public static final SoundEvent n;
    public static final SoundEvent o;
    public static final SoundEvent p;
    public static final SoundEvent q;
    public static final SoundEvent r;
    public static final SoundEvent s;
    public static final SoundEvent t;
    public static final SoundEvent u;
    public static final SoundEvent v;
    public static final SoundEvent w;
    public static final SoundEvent x;
    public static final SoundEvent y;
    public static final SoundEvent z;
    public static final SoundEvent A;
    public static final SoundEvent B;
    public static final SoundEvent C;
    public static final SoundEvent D;
    public static final SoundEvent E;
    public static final SoundEvent F;
    public static final SoundEvent G;
    public static final SoundEvent H;
    public static final SoundEvent I;
    public static final SoundEvent J;
    public static final SoundEvent K;
    public static final SoundEvent L;
    public static final SoundEvent M;
    public static final SoundEvent N;
    public static final SoundEvent O;
    public static final SoundEvent P;
    public static final SoundEvent Q;
    public static final SoundEvent R;
    public static final SoundEvent S;
    public static final SoundEvent T;
    public static final SoundEvent U;
    public static final SoundEvent V;
    public static final SoundEvent W;
    public static final SoundEvent X;
    public static final SoundEvent Y;
    public static final SoundEvent Z;
    public static final SoundEvent aa;
    public static final SoundEvent ab;
    public static final SoundEvent ac;
    public static final SoundEvent ad;
    public static final SoundEvent ae;
    public static final SoundEvent af;
    public static final SoundEvent ag;
    public static final SoundEvent ah;
    public static final SoundEvent ai;
    public static final SoundEvent aj;
    public static final SoundEvent ak;
    public static final SoundEvent al;
    public static final SoundEvent am;
    public static final SoundEvent an;
    public static final SoundEvent ao;
    public static final SoundEvent ap;
    public static final SoundEvent aq;
    public static final SoundEvent ar;
    public static final SoundEvent as;
    public static final SoundEvent at;
    public static final SoundEvent au;
    public static final SoundEvent av;
    public static final SoundEvent aw;
    public static final SoundEvent ax;
    public static final SoundEvent ay;
    public static final SoundEvent az;
    public static final SoundEvent aA;
    public static final SoundEvent aB;
    public static final SoundEvent aC;
    public static final SoundEvent aD;
    public static final SoundEvent aE;
    public static final SoundEvent aF;
    public static final SoundEvent aG;
    public static final SoundEvent aH;
    public static final SoundEvent aI;
    public static final SoundEvent aJ;
    public static final SoundEvent aK;
    public static final SoundEvent aL;
    public static final SoundEvent aM;
    public static final SoundEvent aN;
    public static final SoundEvent aO;
    public static final SoundEvent aP;
    public static final SoundEvent aQ;
    public static final SoundEvent aR;
    public static final SoundEvent aS;
    public static final SoundEvent aT;
    public static final SoundEvent aU;
    public static final SoundEvent aV;
    public static final SoundEvent aW;
    public static final SoundEvent aX;
    public static final SoundEvent aY;
    public static final SoundEvent aZ;
    public static final SoundEvent ba;
    public static final SoundEvent bb;
    public static final SoundEvent bc;
    public static final SoundEvent bd;
    public static final SoundEvent be;
    public static final SoundEvent bf;
    public static final SoundEvent bg;
    public static final SoundEvent bh;
    public static final SoundEvent bi;
    public static final SoundEvent bj;
    public static final SoundEvent bk;
    public static final SoundEvent bl;
    public static final SoundEvent bm;
    public static final SoundEvent bn;
    public static final SoundEvent bo;
    public static final SoundEvent bp;
    public static final SoundEvent bq;
    public static final SoundEvent br;
    public static final SoundEvent bs;
    public static final SoundEvent bt;
    public static final SoundEvent bu;
    public static final SoundEvent bv;
    public static final SoundEvent bw;
    public static final SoundEvent bx;
    public static final SoundEvent by;
    public static final SoundEvent bz;
    public static final SoundEvent bA;
    public static final SoundEvent bB;
    public static final SoundEvent bC;
    public static final SoundEvent bD;
    public static final SoundEvent bE;
    public static final SoundEvent bF;
    public static final SoundEvent bG;
    public static final SoundEvent bH;
    public static final SoundEvent bI;
    public static final SoundEvent bJ;
    public static final SoundEvent bK;
    public static final SoundEvent bL;
    public static final SoundEvent bM;
    public static final SoundEvent bN;
    public static final SoundEvent bO;
    public static final SoundEvent bP;
    public static final SoundEvent bQ;
    public static final SoundEvent bR;
    public static final SoundEvent bS;
    public static final SoundEvent bT;
    public static final SoundEvent bU;
    public static final SoundEvent bV;
    public static final SoundEvent bW;
    public static final SoundEvent bX;
    public static final SoundEvent bY;
    public static final SoundEvent bZ;
    public static final SoundEvent ca;
    public static final SoundEvent cb;
    public static final SoundEvent cc;
    public static final SoundEvent cd;
    public static final SoundEvent ce;
    public static final SoundEvent cf;
    public static final SoundEvent cg;
    public static final SoundEvent ch;
    public static final SoundEvent ci;
    public static final SoundEvent cj;
    public static final SoundEvent ck;
    public static final SoundEvent cl;
    public static final SoundEvent cm;
    public static final SoundEvent cn;
    public static final SoundEvent co;
    public static final SoundEvent cp;
    public static final SoundEvent cq;
    public static final SoundEvent cr;
    public static final SoundEvent cs;
    public static final SoundEvent ct;
    public static final SoundEvent cu;
    public static final SoundEvent cv;
    public static final SoundEvent cw;
    public static final SoundEvent cx;
    public static final SoundEvent cy;
    public static final SoundEvent cz;
    public static final SoundEvent cA;
    public static final SoundEvent cB;
    public static final SoundEvent cC;
    public static final SoundEvent cD;
    public static final SoundEvent cE;
    public static final SoundEvent cF;
    public static final SoundEvent cG;
    public static final SoundEvent cH;
    public static final SoundEvent cI;
    public static final SoundEvent cJ;
    public static final SoundEvent cK;
    public static final SoundEvent cL;
    public static final SoundEvent cM;
    public static final SoundEvent cN;
    public static final SoundEvent cO;
    public static final SoundEvent cP;
    public static final SoundEvent cQ;
    public static final SoundEvent cR;
    public static final SoundEvent cS;
    public static final SoundEvent cT;
    public static final SoundEvent cU;
    public static final SoundEvent cV;
    public static final SoundEvent cW;
    public static final SoundEvent cX;
    public static final SoundEvent cY;
    public static final SoundEvent cZ;
    public static final SoundEvent da;
    public static final SoundEvent db;
    public static final SoundEvent dc;
    public static final SoundEvent dd;
    public static final SoundEvent de;
    public static final SoundEvent df;
    public static final SoundEvent dg;
    public static final SoundEvent dh;
    public static final SoundEvent di;
    public static final SoundEvent dj;
    public static final SoundEvent dk;
    public static final SoundEvent dl;
    public static final SoundEvent dm;
    public static final SoundEvent dn;
    public static final SoundEvent do_;
    public static final SoundEvent dp;
    public static final SoundEvent dq;
    public static final SoundEvent dr;
    public static final SoundEvent ds;
    public static final SoundEvent dt;
    public static final SoundEvent du;
    public static final SoundEvent dv;
    public static final SoundEvent dw;
    public static final SoundEvent dx;
    public static final SoundEvent dy;
    public static final SoundEvent dz;
    public static final SoundEvent dA;
    public static final SoundEvent dB;
    public static final SoundEvent dC;
    public static final SoundEvent dD;
    public static final SoundEvent dE;
    public static final SoundEvent dF;
    public static final SoundEvent dG;
    public static final SoundEvent dH;
    public static final SoundEvent dI;
    public static final SoundEvent dJ;
    public static final SoundEvent dK;
    public static final SoundEvent dL;
    public static final SoundEvent dM;
    public static final SoundEvent dN;
    public static final SoundEvent dO;
    public static final SoundEvent dP;
    public static final SoundEvent dQ;
    public static final SoundEvent dR;
    public static final SoundEvent dS;
    public static final SoundEvent dT;
    public static final SoundEvent dU;
    public static final SoundEvent dV;
    public static final SoundEvent dW;
    public static final SoundEvent dX;
    public static final SoundEvent dY;
    public static final SoundEvent dZ;
    public static final SoundEvent ea;
    public static final SoundEvent eb;
    public static final SoundEvent ec;
    public static final SoundEvent ed;
    public static final SoundEvent ee;
    public static final SoundEvent ef;
    public static final SoundEvent eg;
    public static final SoundEvent eh;
    public static final SoundEvent ei;
    public static final SoundEvent ej;
    public static final SoundEvent ek;
    public static final SoundEvent el;
    public static final SoundEvent em;
    public static final SoundEvent en;
    public static final SoundEvent eo;
    public static final SoundEvent ep;
    public static final SoundEvent eq;
    public static final SoundEvent er;
    public static final SoundEvent es;
    public static final SoundEvent et;
    public static final SoundEvent eu;
    public static final SoundEvent ev;
    public static final SoundEvent ew;
    public static final SoundEvent ex;
    public static final SoundEvent ey;
    public static final SoundEvent ez;
    public static final SoundEvent eA;
    public static final SoundEvent eB;
    public static final SoundEvent eC;
    public static final SoundEvent eD;
    public static final SoundEvent eE;
    public static final SoundEvent eF;
    public static final SoundEvent eG;
    public static final SoundEvent eH;
    public static final SoundEvent eI;
    public static final SoundEvent eJ;
    public static final SoundEvent eK;
    public static final SoundEvent eL;
    public static final SoundEvent eM;
    public static final SoundEvent eN;
    public static final SoundEvent eO;
    public static final SoundEvent eP;
    public static final SoundEvent eQ;
    public static final SoundEvent eR;
    public static final SoundEvent eS;
    public static final SoundEvent eT;
    public static final SoundEvent eU;
    public static final SoundEvent eV;
    public static final SoundEvent eW;
    public static final SoundEvent eX;
    public static final SoundEvent eY;
    public static final SoundEvent eZ;
    public static final SoundEvent fa;
    public static final SoundEvent fb;
    public static final SoundEvent fc;
    public static final SoundEvent fd;
    public static final SoundEvent fe;
    public static final SoundEvent ff;
    public static final SoundEvent fg;
    public static final SoundEvent fh;
    public static final SoundEvent fi;
    public static final SoundEvent fj;
    public static final SoundEvent fk;
    public static final SoundEvent fl;
    public static final SoundEvent fm;
    public static final SoundEvent fn;
    public static final SoundEvent fo;
    public static final SoundEvent fp;
    public static final SoundEvent fq;
    public static final SoundEvent fr;
    public static final SoundEvent fs;
    public static final SoundEvent ft;
    public static final SoundEvent fu;
    public static final SoundEvent fv;
    public static final SoundEvent fw;
    public static final SoundEvent fx;
    public static final SoundEvent fy;
    public static final SoundEvent fz;
    public static final SoundEvent fA;
    public static final SoundEvent fB;
    public static final SoundEvent fC;
    public static final SoundEvent fD;
    public static final SoundEvent fE;
    public static final SoundEvent fF;
    public static final SoundEvent fG;
    public static final SoundEvent fH;
    public static final SoundEvent fI;
    public static final SoundEvent fJ;
    public static final SoundEvent fK;
    public static final SoundEvent fL;
    public static final SoundEvent fM;
    public static final SoundEvent fN;
    public static final SoundEvent fO;
    public static final SoundEvent fP;
    public static final SoundEvent fQ;
    public static final SoundEvent fR;
    public static final SoundEvent fS;
    public static final SoundEvent fT;
    public static final SoundEvent fU;
    public static final SoundEvent fV;
    public static final SoundEvent fW;
    public static final SoundEvent fX;
    public static final SoundEvent fY;
    public static final SoundEvent fZ;
    public static final SoundEvent ga;
    public static final SoundEvent gb;
    public static final SoundEvent gc;
    public static final SoundEvent gd;
    public static final SoundEvent ge;
    public static final SoundEvent gf;
    public static final SoundEvent gg;
    public static final SoundEvent gh;
    public static final SoundEvent gi;
    public static final SoundEvent gj;
    public static final SoundEvent gk;
    public static final SoundEvent gl;
    public static final SoundEvent gm;
    public static final SoundEvent gn;
    public static final SoundEvent go;
    public static final SoundEvent gp;
    public static final SoundEvent gq;
    public static final SoundEvent gr;
    public static final SoundEvent gs;
    public static final SoundEvent gt;
    public static final SoundEvent gu;
    public static final SoundEvent gv;
    public static final SoundEvent gw;
    public static final SoundEvent gx;
    public static final SoundEvent gy;
    public static final SoundEvent gz;
    public static final SoundEvent gA;
    public static final SoundEvent gB;
    public static final SoundEvent gC;
    public static final SoundEvent gD;
    public static final SoundEvent gE;
    public static final SoundEvent gF;
    public static final SoundEvent gG;
    public static final SoundEvent gH;
    public static final SoundEvent gI;
    public static final SoundEvent gJ;
    public static final SoundEvent gK;
    public static final SoundEvent gL;
    public static final SoundEvent gM;
    public static final SoundEvent gN;
    public static final SoundEvent gO;
    public static final SoundEvent gP;
    public static final SoundEvent gQ;
    public static final SoundEvent gR;
    public static final SoundEvent gS;
    public static final SoundEvent gT;
    public static final SoundEvent gU;
    public static final SoundEvent gV;
    public static final SoundEvent gW;
    public static final SoundEvent gX;
    public static final SoundEvent gY;
    public static final SoundEvent gZ;
    public static final SoundEvent ha;
    public static final SoundEvent hb;
    public static final SoundEvent hc;
    public static final SoundEvent hd;
    public static final SoundEvent he;
    public static final SoundEvent hf;
    public static final SoundEvent hg;
    public static final SoundEvent hh;
    public static final SoundEvent hi;
    public static final SoundEvent hj;
    public static final SoundEvent hk;
    public static final SoundEvent hl;
    public static final SoundEvent hm;
    public static final SoundEvent hn;
    public static final SoundEvent ho;
    public static final SoundEvent hp;
    public static final SoundEvent hq;
    public static final SoundEvent hr;
    public static final SoundEvent hs;
    public static final SoundEvent ht;
    public static final SoundEvent hu;
    public static final SoundEvent hv;
    public static final SoundEvent hw;
    public static final SoundEvent hx;
    public static final SoundEvent hy;
    public static final SoundEvent hz;
    public static final SoundEvent hA;
    public static final SoundEvent hB;
    public static final SoundEvent hC;
    public static final SoundEvent hD;
    public static final SoundEvent hE;
    public static final SoundEvent hF;
    public static final SoundEvent hG;
    public static final SoundEvent hH;
    public static final SoundEvent hI;
    public static final SoundEvent hJ;
    public static final SoundEvent hK;
    public static final SoundEvent hL;
    public static final SoundEvent hM;
    public static final SoundEvent hN;
    public static final SoundEvent hO;
    public static final SoundEvent hP;
    public static final SoundEvent hQ;
    public static final SoundEvent hR;
    public static final SoundEvent hS;
    public static final SoundEvent hT;
    public static final SoundEvent hU;
    public static final SoundEvent hV;
    public static final SoundEvent hW;
    public static final SoundEvent hX;
    public static final SoundEvent hY;
    public static final SoundEvent hZ;
    public static final SoundEvent ia;
    public static final SoundEvent ib;
    public static final SoundEvent ic;
    public static final SoundEvent id;
    public static final SoundEvent ie;
    public static final SoundEvent if_;
    public static final SoundEvent ig;
    public static final SoundEvent ih;
    public static final SoundEvent ii;
    public static final SoundEvent ij;
    public static final SoundEvent ik;
    public static final SoundEvent il;
    public static final SoundEvent im;
    public static final SoundEvent in;
    public static final SoundEvent io;
    public static final SoundEvent ip;
    public static final SoundEvent iq;
    public static final SoundEvent ir;
    public static final SoundEvent is;
    public static final SoundEvent it;
    public static final SoundEvent iu;
    public static final SoundEvent iv;
    public static final SoundEvent iw;
    public static final SoundEvent ix;
    public static final SoundEvent iy;
    public static final SoundEvent iz;
    public static final SoundEvent iA;
    public static final SoundEvent iB;
    public static final SoundEvent iC;
    public static final SoundEvent iD;
    public static final SoundEvent iE;
    public static final SoundEvent iF;
    public static final SoundEvent iG;
    public static final SoundEvent iH;
    public static final SoundEvent iI;
    public static final SoundEvent iJ;
    public static final SoundEvent iK;
    public static final SoundEvent iL;
    public static final SoundEvent iM;
    public static final SoundEvent iN;
    public static final SoundEvent iO;
    public static final SoundEvent iP;
    public static final SoundEvent iQ;
    public static final SoundEvent iR;
    public static final SoundEvent iS;
    public static final SoundEvent iT;
    public static final SoundEvent iU;
    public static final SoundEvent iV;
    public static final SoundEvent iW;
    public static final SoundEvent iX;
    public static final SoundEvent iY;
    public static final SoundEvent iZ;
    public static final SoundEvent ja;
    public static final SoundEvent jb;
    public static final SoundEvent jc;
    public static final SoundEvent jd;
    public static final SoundEvent je;
    public static final SoundEvent jf;
    public static final SoundEvent jg;
    public static final SoundEvent jh;
    public static final SoundEvent ji;
    public static final SoundEvent jj;
    public static final SoundEvent jk;
    public static final SoundEvent jl;
    public static final SoundEvent jm;
    public static final SoundEvent jn;
    public static final SoundEvent jo;
    public static final SoundEvent jp;
    public static final SoundEvent jq;
    public static final SoundEvent jr;
    public static final SoundEvent js;
    public static final SoundEvent jt;
    public static final SoundEvent ju;
    public static final SoundEvent jv;
    public static final SoundEvent jw;
    public static final SoundEvent jx;
    public static final SoundEvent jy;
    public static final SoundEvent jz;
    public static final SoundEvent jA;
    public static final SoundEvent jB;
    public static final SoundEvent jC;
    public static final SoundEvent jD;
    public static final SoundEvent jE;
    public static final SoundEvent jF;
    public static final SoundEvent jG;
    public static final SoundEvent jH;
    public static final SoundEvent jI;
    public static final SoundEvent jJ;
    public static final SoundEvent jK;
    public static final SoundEvent jL;
    public static final SoundEvent jM;
    public static final SoundEvent jN;
    public static final SoundEvent jO;
    public static final SoundEvent jP;
    public static final SoundEvent jQ;
    public static final SoundEvent jR;
    public static final SoundEvent jS;
    public static final SoundEvent jT;
    public static final SoundEvent jU;
    public static final SoundEvent jV;
    public static final SoundEvent jW;
    public static final SoundEvent jX;
    public static final SoundEvent jY;
    public static final SoundEvent jZ;
    public static final SoundEvent ka;
    public static final SoundEvent kb;
    public static final SoundEvent kc;
    public static final SoundEvent kd;
    public static final SoundEvent ke;
    public static final SoundEvent kf;
    public static final SoundEvent kg;
    public static final SoundEvent kh;
    public static final SoundEvent ki;
    public static final SoundEvent kj;
    public static final SoundEvent kk;
    public static final SoundEvent kl;
    public static final SoundEvent km;
    public static final SoundEvent kn;
    public static final SoundEvent ko;
    public static final SoundEvent kp;
    public static final SoundEvent kq;
    public static final SoundEvent kr;
    public static final SoundEvent ks;
    public static final SoundEvent kt;
    public static final SoundEvent ku;
    public static final SoundEvent kv;
    public static final SoundEvent kw;
    public static final SoundEvent kx;
    public static final SoundEvent ky;
    public static final SoundEvent kz;
    public static final SoundEvent kA;
    public static final SoundEvent kB;
    public static final SoundEvent kC;
    public static final SoundEvent kD;
    public static final SoundEvent kE;
    public static final SoundEvent kF;
    public static final SoundEvent kG;
    public static final SoundEvent kH;
    public static final SoundEvent kI;
    public static final SoundEvent kJ;
    public static final SoundEvent kK;
    public static final SoundEvent kL;
    public static final SoundEvent kM;
    public static final SoundEvent kN;
    public static final SoundEvent kO;
    public static final SoundEvent kP;
    public static final SoundEvent kQ;
    public static final SoundEvent kR;
    public static final SoundEvent kS;
    public static final SoundEvent kT;
    public static final SoundEvent kU;
    public static final SoundEvent kV;
    public static final SoundEvent kW;
    public static final SoundEvent kX;
    public static final SoundEvent kY;
    public static final SoundEvent kZ;
    public static final SoundEvent la;
    public static final SoundEvent lb;
    public static final SoundEvent lc;
    public static final SoundEvent ld;
    public static final SoundEvent le;
    public static final SoundEvent lf;
    public static final SoundEvent lg;
    public static final SoundEvent lh;
    public static final SoundEvent li;
    public static final SoundEvent lj;
    public static final SoundEvent lk;
    public static final SoundEvent ll;
    public static final SoundEvent lm;
    public static final SoundEvent ln;
    public static final SoundEvent lo;
    public static final SoundEvent lp;
    public static final SoundEvent lq;
    public static final SoundEvent lr;
    public static final SoundEvent ls;
    public static final SoundEvent lt;
    public static final SoundEvent lu;
    public static final SoundEvent lv;
    public static final SoundEvent lw;
    public static final SoundEvent lx;
    public static final SoundEvent ly;
    public static final SoundEvent lz;
    public static final SoundEvent lA;
    public static final SoundEvent lB;
    public static final SoundEvent lC;
    public static final SoundEvent lD;
    public static final SoundEvent lE;
    public static final SoundEvent lF;
    public static final SoundEvent lG;
    public static final SoundEvent lH;
    public static final SoundEvent lI;
    public static final SoundEvent lJ;
    public static final SoundEvent lK;
    public static final SoundEvent lL;
    public static final SoundEvent lM;
    public static final SoundEvent lN;
    public static final SoundEvent lO;
    public static final SoundEvent lP;
    public static final SoundEvent lQ;
    public static final SoundEvent lR;
    public static final SoundEvent lS;
    public static final SoundEvent lT;
    public static final SoundEvent lU;
    public static final SoundEvent lV;
    public static final SoundEvent lW;
    public static final SoundEvent lX;
    public static final SoundEvent lY;
    public static final SoundEvent lZ;
    public static final SoundEvent ma;
    public static final SoundEvent mb;
    public static final SoundEvent mc;
    public static final SoundEvent md;
    public static final SoundEvent me;
    public static final SoundEvent mf;
    public static final SoundEvent mg;
    public static final SoundEvent mh;
    public static final SoundEvent mi;
    public static final SoundEvent mj;
    public static final SoundEvent mk;
    public static final SoundEvent ml;
    public static final SoundEvent mm;
    public static final SoundEvent mn;
    public static final SoundEvent mo;
    public static final SoundEvent mp;
    public static final SoundEvent mq;
    public static final SoundEvent mr;
    public static final SoundEvent ms;
    public static final SoundEvent mt;
    public static final SoundEvent mu;
    public static final SoundEvent mv;
    public static final SoundEvent mw;
    public static final SoundEvent mx;
    public static final SoundEvent my;
    public static final SoundEvent mz;
    public static final SoundEvent mA;
    public static final SoundEvent mB;
    public static final SoundEvent mC;
    public static final SoundEvent mD;
    public static final SoundEvent mE;
    public static final SoundEvent mF;
    public static final SoundEvent mG;
    public static final SoundEvent mH;
    public static final SoundEvent mI;
    public static final SoundEvent mJ;
    public static final SoundEvent mK;
    public static final SoundEvent mL;
    public static final SoundEvent mM;
    public static final SoundEvent mN;
    public static final SoundEvent mO;
    public static final SoundEvent mP;
    public static final SoundEvent mQ;
    public static final SoundEvent mR;
    public static final SoundEvent mS;
    public static final SoundEvent mT;
    public static final SoundEvent mU;
    public static final SoundEvent mV;
    public static final SoundEvent mW;
    public static final SoundEvent mX;
    public static final SoundEvent mY;
    public static final SoundEvent mZ;
    public static final SoundEvent na;
    public static final SoundEvent nb;
    public static final SoundEvent nc;
    public static final SoundEvent nd;
    public static final SoundEvent ne;
    public static final SoundEvent nf;
    public static final SoundEvent ng;
    public static final SoundEvent nh;
    public static final SoundEvent ni;
    public static final SoundEvent nj;
    public static final SoundEvent nk;
    public static final SoundEvent nl;
    public static final SoundEvent nm;
    public static final SoundEvent nn;
    public static final SoundEvent no;
    public static final SoundEvent np;
    public static final SoundEvent nq;
    public static final SoundEvent nr;
    public static final SoundEvent ns;
    public static final SoundEvent nt;
    public static final SoundEvent nu;
    public static final SoundEvent nv;
    public static final SoundEvent nw;
    public static final SoundEvent nx;
    public static final SoundEvent ny;
    public static final SoundEvent nz;
    public static final SoundEvent nA;
    public static final SoundEvent nB;
    public static final SoundEvent nC;
    public static final SoundEvent nD;
    public static final SoundEvent nE;
    public static final SoundEvent nF;
    public static final SoundEvent nG;
    public static final SoundEvent nH;
    public static final SoundEvent nI;
    public static final SoundEvent nJ;
    public static final SoundEvent nK;
    public static final SoundEvent nL;
    public static final SoundEvent nM;
    public static final SoundEvent nN;
    public static final SoundEvent nO;
    public static final SoundEvent nP;
    public static final SoundEvent nQ;
    public static final SoundEvent nR;
    public static final SoundEvent nS;
    public static final SoundEvent nT;
    public static final SoundEvent nU;
    public static final SoundEvent nV;
    public static final SoundEvent nW;
    public static final SoundEvent nX;
    public static final SoundEvent nY;
    public static final SoundEvent nZ;
    public static final SoundEvent oa;
    public static final SoundEvent ob;
    public static final SoundEvent oc;
    public static final SoundEvent od;
    public static final SoundEvent oe;
    public static final SoundEvent of;
    public static final SoundEvent og;
    public static final SoundEvent oh;
    public static final SoundEvent oi;
    public static final SoundEvent oj;
    public static final SoundEvent ok;
    public static final SoundEvent ol;
    public static final SoundEvent om;
    public static final SoundEvent on;
    public static final SoundEvent oo;
    
    private static SoundEvent register(final String id) {
        return Registry.<SoundEvent>register(Registry.SOUND_EVENT, id, new SoundEvent(new Identifier(id)));
    }
    
    static {
        a = register("ambient.cave");
        b = register("ambient.underwater.enter");
        c = register("ambient.underwater.exit");
        d = register("ambient.underwater.loop");
        e = register("ambient.underwater.loop.additions");
        f = register("ambient.underwater.loop.additions.rare");
        g = register("ambient.underwater.loop.additions.ultra_rare");
        h = register("block.anvil.break");
        i = register("block.anvil.destroy");
        j = register("block.anvil.fall");
        k = register("block.anvil.hit");
        l = register("block.anvil.land");
        m = register("block.anvil.place");
        n = register("block.anvil.step");
        o = register("block.anvil.use");
        p = register("item.armor.equip_chain");
        q = register("item.armor.equip_diamond");
        r = register("item.armor.equip_elytra");
        s = register("item.armor.equip_generic");
        t = register("item.armor.equip_gold");
        u = register("item.armor.equip_iron");
        v = register("item.armor.equip_leather");
        w = register("item.armor.equip_turtle");
        x = register("entity.armor_stand.break");
        y = register("entity.armor_stand.fall");
        z = register("entity.armor_stand.hit");
        A = register("entity.armor_stand.place");
        B = register("entity.arrow.hit");
        C = register("entity.arrow.hit_player");
        D = register("entity.arrow.shoot");
        E = register("item.axe.strip");
        F = register("block.bamboo.break");
        G = register("block.bamboo.fall");
        H = register("block.bamboo.hit");
        I = register("block.bamboo.place");
        J = register("block.bamboo.step");
        K = register("block.bamboo_sapling.break");
        L = register("block.bamboo_sapling.hit");
        M = register("block.bamboo_sapling.place");
        N = register("block.barrel.close");
        O = register("block.barrel.open");
        P = register("entity.bat.ambient");
        Q = register("entity.bat.death");
        R = register("entity.bat.hurt");
        S = register("entity.bat.loop");
        T = register("entity.bat.takeoff");
        U = register("block.beacon.activate");
        V = register("block.beacon.ambient");
        W = register("block.beacon.deactivate");
        X = register("block.beacon.power_select");
        Y = register("block.bell.use");
        Z = register("block.bell.resonate");
        aa = register("entity.blaze.ambient");
        ab = register("entity.blaze.burn");
        ac = register("entity.blaze.death");
        ad = register("entity.blaze.hurt");
        ae = register("entity.blaze.shoot");
        af = register("entity.boat.paddle_land");
        ag = register("entity.boat.paddle_water");
        ah = register("item.book.page_turn");
        ai = register("item.book.put");
        aj = register("entity.fishing_bobber.retrieve");
        ak = register("entity.fishing_bobber.splash");
        al = register("entity.fishing_bobber.throw");
        am = register("block.blastfurnace.fire_crackle");
        an = register("item.bottle.empty");
        ao = register("item.bottle.fill");
        ap = register("item.bottle.fill_dragonbreath");
        aq = register("block.brewing_stand.brew");
        ar = register("block.bubble_column.bubble_pop");
        as = register("block.bubble_column.upwards_ambient");
        at = register("block.bubble_column.upwards_inside");
        au = register("block.bubble_column.whirlpool_ambient");
        av = register("block.bubble_column.whirlpool_inside");
        aw = register("item.bucket.empty");
        ax = register("item.bucket.empty_fish");
        ay = register("item.bucket.empty_lava");
        az = register("item.bucket.fill");
        aA = register("item.bucket.fill_fish");
        aB = register("item.bucket.fill_lava");
        aC = register("block.campfire.crackle");
        aD = register("entity.cat.ambient");
        aE = register("entity.cat.stray_ambient");
        aF = register("entity.cat.death");
        aG = register("entity.cat.eat");
        aH = register("entity.cat.hiss");
        aI = register("entity.cat.beg_for_food");
        aJ = register("entity.cat.hurt");
        aK = register("entity.cat.purr");
        aL = register("entity.cat.purreow");
        aM = register("block.chest.close");
        aN = register("block.chest.locked");
        aO = register("block.chest.open");
        aP = register("entity.chicken.ambient");
        aQ = register("entity.chicken.death");
        aR = register("entity.chicken.egg");
        aS = register("entity.chicken.hurt");
        aT = register("entity.chicken.step");
        aU = register("block.chorus_flower.death");
        aV = register("block.chorus_flower.grow");
        aW = register("item.chorus_fruit.teleport");
        aX = register("block.wool.break");
        aY = register("block.wool.fall");
        aZ = register("block.wool.hit");
        ba = register("block.wool.place");
        bb = register("block.wool.step");
        bc = register("entity.cod.ambient");
        bd = register("entity.cod.death");
        be = register("entity.cod.flop");
        bf = register("entity.cod.hurt");
        bg = register("block.comparator.click");
        bh = register("block.composter.empty");
        bi = register("block.composter.fill");
        bj = register("block.composter.fill_success");
        bk = register("block.composter.ready");
        bl = register("block.conduit.activate");
        bm = register("block.conduit.ambient");
        bn = register("block.conduit.ambient.short");
        bo = register("block.conduit.attack.target");
        bp = register("block.conduit.deactivate");
        bq = register("entity.cow.ambient");
        br = register("entity.cow.death");
        bs = register("entity.cow.hurt");
        bt = register("entity.cow.milk");
        bu = register("entity.cow.step");
        bv = register("entity.creeper.death");
        bw = register("entity.creeper.hurt");
        bx = register("entity.creeper.primed");
        by = register("block.crop.break");
        bz = register("item.crop.plant");
        bA = register("item.crossbow.hit");
        bB = register("item.crossbow.loading_end");
        bC = register("item.crossbow.loading_middle");
        bD = register("item.crossbow.loading_start");
        bE = register("item.crossbow.quick_charge_1");
        bF = register("item.crossbow.quick_charge_2");
        bG = register("item.crossbow.quick_charge_3");
        bH = register("item.crossbow.shoot");
        bI = register("block.dispenser.dispense");
        bJ = register("block.dispenser.fail");
        bK = register("block.dispenser.launch");
        bL = register("entity.dolphin.ambient");
        bM = register("entity.dolphin.ambient_water");
        bN = register("entity.dolphin.attack");
        bO = register("entity.dolphin.death");
        bP = register("entity.dolphin.eat");
        bQ = register("entity.dolphin.hurt");
        bR = register("entity.dolphin.jump");
        bS = register("entity.dolphin.play");
        bT = register("entity.dolphin.splash");
        bU = register("entity.dolphin.swim");
        bV = register("entity.donkey.ambient");
        bW = register("entity.donkey.angry");
        bX = register("entity.donkey.chest");
        bY = register("entity.donkey.death");
        bZ = register("entity.donkey.hurt");
        ca = register("entity.drowned.ambient");
        cb = register("entity.drowned.ambient_water");
        cc = register("entity.drowned.death");
        cd = register("entity.drowned.death_water");
        ce = register("entity.drowned.hurt");
        cf = register("entity.drowned.hurt_water");
        cg = register("entity.drowned.shoot");
        ch = register("entity.drowned.step");
        ci = register("entity.drowned.swim");
        cj = register("entity.egg.throw");
        ck = register("entity.elder_guardian.ambient");
        cl = register("entity.elder_guardian.ambient_land");
        cm = register("entity.elder_guardian.curse");
        cn = register("entity.elder_guardian.death");
        co = register("entity.elder_guardian.death_land");
        cp = register("entity.elder_guardian.flop");
        cq = register("entity.elder_guardian.hurt");
        cr = register("entity.elder_guardian.hurt_land");
        cs = register("item.elytra.flying");
        ct = register("block.enchantment_table.use");
        cu = register("block.ender_chest.close");
        cv = register("block.ender_chest.open");
        cw = register("entity.ender_dragon.ambient");
        cx = register("entity.ender_dragon.death");
        cy = register("entity.dragon_fireball.explode");
        cz = register("entity.ender_dragon.flap");
        cA = register("entity.ender_dragon.growl");
        cB = register("entity.ender_dragon.hurt");
        cC = register("entity.ender_dragon.shoot");
        cD = register("entity.ender_eye.death");
        cE = register("entity.ender_eye.launch");
        cF = register("entity.enderman.ambient");
        cG = register("entity.enderman.death");
        cH = register("entity.enderman.hurt");
        cI = register("entity.enderman.scream");
        cJ = register("entity.enderman.stare");
        cK = register("entity.enderman.teleport");
        cL = register("entity.endermite.ambient");
        cM = register("entity.endermite.death");
        cN = register("entity.endermite.hurt");
        cO = register("entity.endermite.step");
        cP = register("entity.ender_pearl.throw");
        cQ = register("block.end_gateway.spawn");
        cR = register("block.end_portal_frame.fill");
        cS = register("block.end_portal.spawn");
        cT = register("entity.evoker.ambient");
        cU = register("entity.evoker.cast_spell");
        cV = register("entity.evoker.celebrate");
        cW = register("entity.evoker.death");
        cX = register("entity.evoker_fangs.attack");
        cY = register("entity.evoker.hurt");
        cZ = register("entity.evoker.prepare_attack");
        da = register("entity.evoker.prepare_summon");
        db = register("entity.evoker.prepare_wololo");
        dc = register("entity.experience_bottle.throw");
        dd = register("entity.experience_orb.pickup");
        de = register("block.fence_gate.close");
        df = register("block.fence_gate.open");
        dg = register("item.firecharge.use");
        dh = register("entity.firework_rocket.blast");
        di = register("entity.firework_rocket.blast_far");
        dj = register("entity.firework_rocket.large_blast");
        dk = register("entity.firework_rocket.large_blast_far");
        dl = register("entity.firework_rocket.launch");
        dm = register("entity.firework_rocket.shoot");
        dn = register("entity.firework_rocket.twinkle");
        do_ = register("entity.firework_rocket.twinkle_far");
        dp = register("block.fire.ambient");
        dq = register("block.fire.extinguish");
        dr = register("entity.fish.swim");
        ds = register("item.flintandsteel.use");
        dt = register("entity.fox.aggro");
        du = register("entity.fox.ambient");
        dv = register("entity.fox.bite");
        dw = register("entity.fox.death");
        dx = register("entity.fox.eat");
        dy = register("entity.fox.hurt");
        dz = register("entity.fox.screech");
        dA = register("entity.fox.sleep");
        dB = register("entity.fox.sniff");
        dC = register("entity.fox.spit");
        dD = register("block.furnace.fire_crackle");
        dE = register("entity.generic.big_fall");
        dF = register("entity.generic.burn");
        dG = register("entity.generic.death");
        dH = register("entity.generic.drink");
        dI = register("entity.generic.eat");
        dJ = register("entity.generic.explode");
        dK = register("entity.generic.extinguish_fire");
        dL = register("entity.generic.hurt");
        dM = register("entity.generic.small_fall");
        dN = register("entity.generic.splash");
        dO = register("entity.generic.swim");
        dP = register("entity.ghast.ambient");
        dQ = register("entity.ghast.death");
        dR = register("entity.ghast.hurt");
        dS = register("entity.ghast.scream");
        dT = register("entity.ghast.shoot");
        dU = register("entity.ghast.warn");
        dV = register("block.glass.break");
        dW = register("block.glass.fall");
        dX = register("block.glass.hit");
        dY = register("block.glass.place");
        dZ = register("block.glass.step");
        ea = register("block.grass.break");
        eb = register("block.grass.fall");
        ec = register("block.grass.hit");
        ed = register("block.grass.place");
        ee = register("block.grass.step");
        ef = register("block.wet_grass.break");
        eg = register("block.wet_grass.fall");
        eh = register("block.wet_grass.hit");
        ei = register("block.wet_grass.place");
        ej = register("block.wet_grass.step");
        ek = register("block.coral_block.break");
        el = register("block.coral_block.fall");
        em = register("block.coral_block.hit");
        en = register("block.coral_block.place");
        eo = register("block.coral_block.step");
        ep = register("block.gravel.break");
        eq = register("block.gravel.fall");
        er = register("block.gravel.hit");
        es = register("block.gravel.place");
        et = register("block.gravel.step");
        eu = register("block.grindstone.use");
        ev = register("entity.guardian.ambient");
        ew = register("entity.guardian.ambient_land");
        ex = register("entity.guardian.attack");
        ey = register("entity.guardian.death");
        ez = register("entity.guardian.death_land");
        eA = register("entity.guardian.flop");
        eB = register("entity.guardian.hurt");
        eC = register("entity.guardian.hurt_land");
        eD = register("item.hoe.till");
        eE = register("entity.horse.ambient");
        eF = register("entity.horse.angry");
        eG = register("entity.horse.armor");
        eH = register("entity.horse.breathe");
        eI = register("entity.horse.death");
        eJ = register("entity.horse.eat");
        eK = register("entity.horse.gallop");
        eL = register("entity.horse.hurt");
        eM = register("entity.horse.jump");
        eN = register("entity.horse.land");
        eO = register("entity.horse.saddle");
        eP = register("entity.horse.step");
        eQ = register("entity.horse.step_wood");
        eR = register("entity.hostile.big_fall");
        eS = register("entity.hostile.death");
        eT = register("entity.hostile.hurt");
        eU = register("entity.hostile.small_fall");
        eV = register("entity.hostile.splash");
        eW = register("entity.hostile.swim");
        eX = register("entity.husk.ambient");
        eY = register("entity.husk.converted_to_zombie");
        eZ = register("entity.husk.death");
        fa = register("entity.husk.hurt");
        fb = register("entity.husk.step");
        fc = register("entity.ravager.ambient");
        fd = register("entity.ravager.attack");
        fe = register("entity.ravager.celebrate");
        ff = register("entity.ravager.death");
        fg = register("entity.ravager.hurt");
        fh = register("entity.ravager.step");
        fi = register("entity.ravager.stunned");
        fj = register("entity.ravager.roar");
        fk = register("entity.illusioner.ambient");
        fl = register("entity.illusioner.cast_spell");
        fm = register("entity.illusioner.death");
        fn = register("entity.illusioner.hurt");
        fo = register("entity.illusioner.mirror_move");
        fp = register("entity.illusioner.prepare_blindness");
        fq = register("entity.illusioner.prepare_mirror");
        fr = register("block.iron_door.close");
        fs = register("block.iron_door.open");
        ft = register("entity.iron_golem.attack");
        fu = register("entity.iron_golem.death");
        fv = register("entity.iron_golem.hurt");
        fw = register("entity.iron_golem.step");
        fx = register("block.iron_trapdoor.close");
        fy = register("block.iron_trapdoor.open");
        fz = register("entity.item_frame.add_item");
        fA = register("entity.item_frame.break");
        fB = register("entity.item_frame.place");
        fC = register("entity.item_frame.remove_item");
        fD = register("entity.item_frame.rotate_item");
        fE = register("entity.item.break");
        fF = register("entity.item.pickup");
        fG = register("block.ladder.break");
        fH = register("block.ladder.fall");
        fI = register("block.ladder.hit");
        fJ = register("block.ladder.place");
        fK = register("block.ladder.step");
        fL = register("block.lantern.break");
        fM = register("block.lantern.fall");
        fN = register("block.lantern.hit");
        fO = register("block.lantern.place");
        fP = register("block.lantern.step");
        fQ = register("block.lava.ambient");
        fR = register("block.lava.extinguish");
        fS = register("block.lava.pop");
        fT = register("entity.leash_knot.break");
        fU = register("entity.leash_knot.place");
        fV = register("block.lever.click");
        fW = register("entity.lightning_bolt.impact");
        fX = register("entity.lightning_bolt.thunder");
        fY = register("entity.lingering_potion.throw");
        fZ = register("entity.llama.ambient");
        ga = register("entity.llama.angry");
        gb = register("entity.llama.chest");
        gc = register("entity.llama.death");
        gd = register("entity.llama.eat");
        ge = register("entity.llama.hurt");
        gf = register("entity.llama.spit");
        gg = register("entity.llama.step");
        gh = register("entity.llama.swag");
        gi = register("entity.magma_cube.death");
        gj = register("entity.magma_cube.hurt");
        gk = register("entity.magma_cube.jump");
        gl = register("entity.magma_cube.squish");
        gm = register("block.metal.break");
        gn = register("block.metal.fall");
        go = register("block.metal.hit");
        gp = register("block.metal.place");
        gq = register("block.metal_pressure_plate.click_off");
        gr = register("block.metal_pressure_plate.click_on");
        gs = register("block.metal.step");
        gt = register("entity.minecart.inside");
        gu = register("entity.minecart.riding");
        gv = register("entity.mooshroom.convert");
        gw = register("entity.mooshroom.eat");
        gx = register("entity.mooshroom.milk");
        gy = register("entity.mooshroom.suspicious_milk");
        gz = register("entity.mooshroom.shear");
        gA = register("entity.mule.ambient");
        gB = register("entity.mule.chest");
        gC = register("entity.mule.death");
        gD = register("entity.mule.hurt");
        gE = register("music.creative");
        gF = register("music.credits");
        gG = register("music.dragon");
        gH = register("music.end");
        gI = register("music.game");
        gJ = register("music.menu");
        gK = register("music.nether");
        gL = register("music.under_water");
        gM = register("block.nether_wart.break");
        gN = register("item.nether_wart.plant");
        gO = register("block.note_block.basedrum");
        gP = register("block.note_block.bass");
        gQ = register("block.note_block.bell");
        gR = register("block.note_block.chime");
        gS = register("block.note_block.flute");
        gT = register("block.note_block.guitar");
        gU = register("block.note_block.harp");
        gV = register("block.note_block.hat");
        gW = register("block.note_block.pling");
        gX = register("block.note_block.snare");
        gY = register("block.note_block.xylophone");
        gZ = register("block.note_block.iron_xylophone");
        ha = register("block.note_block.cow_bell");
        hb = register("block.note_block.didgeridoo");
        hc = register("block.note_block.bit");
        hd = register("block.note_block.banjo");
        he = register("entity.ocelot.hurt");
        hf = register("entity.ocelot.ambient");
        hg = register("entity.ocelot.death");
        hh = register("entity.painting.break");
        hi = register("entity.painting.place");
        hj = register("entity.panda.pre_sneeze");
        hk = register("entity.panda.sneeze");
        hl = register("entity.panda.ambient");
        hm = register("entity.panda.death");
        hn = register("entity.panda.eat");
        ho = register("entity.panda.step");
        hp = register("entity.panda.cant_breed");
        hq = register("entity.panda.aggressive_ambient");
        hr = register("entity.panda.worried_ambient");
        hs = register("entity.panda.hurt");
        ht = register("entity.panda.bite");
        hu = register("entity.parrot.ambient");
        hv = register("entity.parrot.death");
        hw = register("entity.parrot.eat");
        hx = register("entity.parrot.fly");
        hy = register("entity.parrot.hurt");
        hz = register("entity.parrot.imitate.blaze");
        hA = register("entity.parrot.imitate.creeper");
        hB = register("entity.parrot.imitate.drowned");
        hC = register("entity.parrot.imitate.elder_guardian");
        hD = register("entity.parrot.imitate.ender_dragon");
        hE = register("entity.parrot.imitate.enderman");
        hF = register("entity.parrot.imitate.endermite");
        hG = register("entity.parrot.imitate.evoker");
        hH = register("entity.parrot.imitate.ghast");
        hI = register("entity.parrot.imitate.guardian");
        hJ = register("entity.parrot.imitate.husk");
        hK = register("entity.parrot.imitate.illusioner");
        hL = register("entity.parrot.imitate.magma_cube");
        hM = register("entity.parrot.imitate.panda");
        hN = register("entity.parrot.imitate.phantom");
        hO = register("entity.parrot.imitate.pillager");
        hP = register("entity.parrot.imitate.polar_bear");
        hQ = register("entity.parrot.imitate.ravager");
        hR = register("entity.parrot.imitate.shulker");
        hS = register("entity.parrot.imitate.silverfish");
        hT = register("entity.parrot.imitate.skeleton");
        hU = register("entity.parrot.imitate.slime");
        hV = register("entity.parrot.imitate.spider");
        hW = register("entity.parrot.imitate.stray");
        hX = register("entity.parrot.imitate.vex");
        hY = register("entity.parrot.imitate.vindicator");
        hZ = register("entity.parrot.imitate.witch");
        ia = register("entity.parrot.imitate.wither");
        ib = register("entity.parrot.imitate.wither_skeleton");
        ic = register("entity.parrot.imitate.wolf");
        id = register("entity.parrot.imitate.zombie");
        ie = register("entity.parrot.imitate.zombie_pigman");
        if_ = register("entity.parrot.imitate.zombie_villager");
        ig = register("entity.parrot.step");
        ih = register("entity.phantom.ambient");
        ii = register("entity.phantom.bite");
        ij = register("entity.phantom.death");
        ik = register("entity.phantom.flap");
        il = register("entity.phantom.hurt");
        im = register("entity.phantom.swoop");
        in = register("entity.pig.ambient");
        io = register("entity.pig.death");
        ip = register("entity.pig.hurt");
        iq = register("entity.pig.saddle");
        ir = register("entity.pig.step");
        is = register("entity.pillager.ambient");
        it = register("entity.pillager.celebrate");
        iu = register("entity.pillager.death");
        iv = register("entity.pillager.hurt");
        iw = register("block.piston.contract");
        ix = register("block.piston.extend");
        iy = register("entity.player.attack.crit");
        iz = register("entity.player.attack.knockback");
        iA = register("entity.player.attack.nodamage");
        iB = register("entity.player.attack.strong");
        iC = register("entity.player.attack.sweep");
        iD = register("entity.player.attack.weak");
        iE = register("entity.player.big_fall");
        iF = register("entity.player.breath");
        iG = register("entity.player.burp");
        iH = register("entity.player.death");
        iI = register("entity.player.hurt");
        iJ = register("entity.player.hurt_drown");
        iK = register("entity.player.hurt_on_fire");
        iL = register("entity.player.hurt_sweet_berry_bush");
        iM = register("entity.player.levelup");
        iN = register("entity.player.small_fall");
        iO = register("entity.player.splash");
        iP = register("entity.player.splash.high_speed");
        iQ = register("entity.player.swim");
        iR = register("entity.polar_bear.ambient");
        iS = register("entity.polar_bear.ambient_baby");
        iT = register("entity.polar_bear.death");
        iU = register("entity.polar_bear.hurt");
        iV = register("entity.polar_bear.step");
        iW = register("entity.polar_bear.warning");
        iX = register("block.portal.ambient");
        iY = register("block.portal.travel");
        iZ = register("block.portal.trigger");
        ja = register("entity.puffer_fish.ambient");
        jb = register("entity.puffer_fish.blow_out");
        jc = register("entity.puffer_fish.blow_up");
        jd = register("entity.puffer_fish.death");
        je = register("entity.puffer_fish.flop");
        jf = register("entity.puffer_fish.hurt");
        jg = register("entity.puffer_fish.sting");
        jh = register("block.pumpkin.carve");
        ji = register("entity.rabbit.ambient");
        jj = register("entity.rabbit.attack");
        jk = register("entity.rabbit.death");
        jl = register("entity.rabbit.hurt");
        jm = register("entity.rabbit.jump");
        jn = register("event.raid.horn");
        jo = register("music_disc.11");
        jp = register("music_disc.13");
        jq = register("music_disc.blocks");
        jr = register("music_disc.cat");
        js = register("music_disc.chirp");
        jt = register("music_disc.far");
        ju = register("music_disc.mall");
        jv = register("music_disc.mellohi");
        jw = register("music_disc.stal");
        jx = register("music_disc.strad");
        jy = register("music_disc.wait");
        jz = register("music_disc.ward");
        jA = register("block.redstone_torch.burnout");
        jB = register("entity.salmon.ambient");
        jC = register("entity.salmon.death");
        jD = register("entity.salmon.flop");
        jE = register("entity.salmon.hurt");
        jF = register("block.sand.break");
        jG = register("block.sand.fall");
        jH = register("block.sand.hit");
        jI = register("block.sand.place");
        jJ = register("block.sand.step");
        jK = register("block.scaffolding.break");
        jL = register("block.scaffolding.fall");
        jM = register("block.scaffolding.hit");
        jN = register("block.scaffolding.place");
        jO = register("block.scaffolding.step");
        jP = register("entity.sheep.ambient");
        jQ = register("entity.sheep.death");
        jR = register("entity.sheep.hurt");
        jS = register("entity.sheep.shear");
        jT = register("entity.sheep.step");
        jU = register("item.shield.block");
        jV = register("item.shield.break");
        jW = register("item.shovel.flatten");
        jX = register("entity.shulker.ambient");
        jY = register("block.shulker_box.close");
        jZ = register("block.shulker_box.open");
        ka = register("entity.shulker_bullet.hit");
        kb = register("entity.shulker_bullet.hurt");
        kc = register("entity.shulker.close");
        kd = register("entity.shulker.death");
        ke = register("entity.shulker.hurt");
        kf = register("entity.shulker.hurt_closed");
        kg = register("entity.shulker.open");
        kh = register("entity.shulker.shoot");
        ki = register("entity.shulker.teleport");
        kj = register("entity.silverfish.ambient");
        kk = register("entity.silverfish.death");
        kl = register("entity.silverfish.hurt");
        km = register("entity.silverfish.step");
        kn = register("entity.skeleton.ambient");
        ko = register("entity.skeleton.death");
        kp = register("entity.skeleton_horse.ambient");
        kq = register("entity.skeleton_horse.death");
        kr = register("entity.skeleton_horse.hurt");
        ks = register("entity.skeleton_horse.swim");
        kt = register("entity.skeleton_horse.ambient_water");
        ku = register("entity.skeleton_horse.gallop_water");
        kv = register("entity.skeleton_horse.jump_water");
        kw = register("entity.skeleton_horse.step_water");
        kx = register("entity.skeleton.hurt");
        ky = register("entity.skeleton.shoot");
        kz = register("entity.skeleton.step");
        kA = register("entity.slime.attack");
        kB = register("entity.slime.death");
        kC = register("entity.slime.hurt");
        kD = register("entity.slime.jump");
        kE = register("entity.slime.squish");
        kF = register("block.slime_block.break");
        kG = register("block.slime_block.fall");
        kH = register("block.slime_block.hit");
        kI = register("block.slime_block.place");
        kJ = register("block.slime_block.step");
        kK = register("entity.magma_cube.death_small");
        kL = register("entity.magma_cube.hurt_small");
        kM = register("entity.magma_cube.squish_small");
        kN = register("entity.slime.death_small");
        kO = register("entity.slime.hurt_small");
        kP = register("entity.slime.jump_small");
        kQ = register("entity.slime.squish_small");
        kR = register("block.smoker.smoke");
        kS = register("entity.snowball.throw");
        kT = register("block.snow.break");
        kU = register("block.snow.fall");
        kV = register("entity.snow_golem.ambient");
        kW = register("entity.snow_golem.death");
        kX = register("entity.snow_golem.hurt");
        kY = register("entity.snow_golem.shoot");
        kZ = register("block.snow.hit");
        la = register("block.snow.place");
        lb = register("block.snow.step");
        lc = register("entity.spider.ambient");
        ld = register("entity.spider.death");
        le = register("entity.spider.hurt");
        lf = register("entity.spider.step");
        lg = register("entity.splash_potion.break");
        lh = register("entity.splash_potion.throw");
        li = register("entity.squid.ambient");
        lj = register("entity.squid.death");
        lk = register("entity.squid.hurt");
        ll = register("entity.squid.squirt");
        lm = register("block.stone.break");
        ln = register("block.stone_button.click_off");
        lo = register("block.stone_button.click_on");
        lp = register("block.stone.fall");
        lq = register("block.stone.hit");
        lr = register("block.stone.place");
        ls = register("block.stone_pressure_plate.click_off");
        lt = register("block.stone_pressure_plate.click_on");
        lu = register("block.stone.step");
        lv = register("entity.stray.ambient");
        lw = register("entity.stray.death");
        lx = register("entity.stray.hurt");
        ly = register("entity.stray.step");
        lz = register("block.sweet_berry_bush.break");
        lA = register("block.sweet_berry_bush.place");
        lB = register("item.sweet_berries.pick_from_bush");
        lC = register("enchant.thorns.hit");
        lD = register("entity.tnt.primed");
        lE = register("item.totem.use");
        lF = register("item.trident.hit");
        lG = register("item.trident.hit_ground");
        lH = register("item.trident.return");
        lI = register("item.trident.riptide_1");
        lJ = register("item.trident.riptide_2");
        lK = register("item.trident.riptide_3");
        lL = register("item.trident.throw");
        lM = register("item.trident.thunder");
        lN = register("block.tripwire.attach");
        lO = register("block.tripwire.click_off");
        lP = register("block.tripwire.click_on");
        lQ = register("block.tripwire.detach");
        lR = register("entity.tropical_fish.ambient");
        lS = register("entity.tropical_fish.death");
        lT = register("entity.tropical_fish.flop");
        lU = register("entity.tropical_fish.hurt");
        lV = register("entity.turtle.ambient_land");
        lW = register("entity.turtle.death");
        lX = register("entity.turtle.death_baby");
        lY = register("entity.turtle.egg_break");
        lZ = register("entity.turtle.egg_crack");
        ma = register("entity.turtle.egg_hatch");
        mb = register("entity.turtle.hurt");
        mc = register("entity.turtle.hurt_baby");
        md = register("entity.turtle.lay_egg");
        me = register("entity.turtle.shamble");
        mf = register("entity.turtle.shamble_baby");
        mg = register("entity.turtle.swim");
        mh = register("ui.button.click");
        mi = register("ui.loom.select_pattern");
        mj = register("ui.loom.take_result");
        mk = register("ui.cartography_table.take_result");
        ml = register("ui.stonecutter.take_result");
        mm = register("ui.stonecutter.select_recipe");
        mn = register("ui.toast.challenge_complete");
        mo = register("ui.toast.in");
        mp = register("ui.toast.out");
        mq = register("entity.vex.ambient");
        mr = register("entity.vex.charge");
        ms = register("entity.vex.death");
        mt = register("entity.vex.hurt");
        mu = register("entity.villager.ambient");
        mv = register("entity.villager.celebrate");
        mw = register("entity.villager.death");
        mx = register("entity.villager.hurt");
        my = register("entity.villager.no");
        mz = register("entity.villager.trade");
        mA = register("entity.villager.yes");
        mB = register("entity.villager.work_armorer");
        mC = register("entity.villager.work_butcher");
        mD = register("entity.villager.work_cartographer");
        mE = register("entity.villager.work_cleric");
        mF = register("entity.villager.work_farmer");
        mG = register("entity.villager.work_fisherman");
        mH = register("entity.villager.work_fletcher");
        mI = register("entity.villager.work_leatherworker");
        mJ = register("entity.villager.work_librarian");
        mK = register("entity.villager.work_mason");
        mL = register("entity.villager.work_shepherd");
        mM = register("entity.villager.work_toolsmith");
        mN = register("entity.villager.work_weaponsmith");
        mO = register("entity.vindicator.ambient");
        mP = register("entity.vindicator.celebrate");
        mQ = register("entity.vindicator.death");
        mR = register("entity.vindicator.hurt");
        mS = register("block.lily_pad.place");
        mT = register("entity.wandering_trader.ambient");
        mU = register("entity.wandering_trader.death");
        mV = register("entity.wandering_trader.disappeared");
        mW = register("entity.wandering_trader.drink_milk");
        mX = register("entity.wandering_trader.drink_potion");
        mY = register("entity.wandering_trader.hurt");
        mZ = register("entity.wandering_trader.no");
        na = register("entity.wandering_trader.reappeared");
        nb = register("entity.wandering_trader.trade");
        nc = register("entity.wandering_trader.yes");
        nd = register("block.water.ambient");
        ne = register("weather.rain");
        nf = register("weather.rain.above");
        ng = register("entity.witch.ambient");
        nh = register("entity.witch.celebrate");
        ni = register("entity.witch.death");
        nj = register("entity.witch.drink");
        nk = register("entity.witch.hurt");
        nl = register("entity.witch.throw");
        nm = register("entity.wither.ambient");
        nn = register("entity.wither.break_block");
        no = register("entity.wither.death");
        np = register("entity.wither.hurt");
        nq = register("entity.wither.shoot");
        nr = register("entity.wither_skeleton.ambient");
        ns = register("entity.wither_skeleton.death");
        nt = register("entity.wither_skeleton.hurt");
        nu = register("entity.wither_skeleton.step");
        nv = register("entity.wither.spawn");
        nw = register("entity.wolf.ambient");
        nx = register("entity.wolf.death");
        ny = register("entity.wolf.growl");
        nz = register("entity.wolf.howl");
        nA = register("entity.wolf.hurt");
        nB = register("entity.wolf.pant");
        nC = register("entity.wolf.shake");
        nD = register("entity.wolf.step");
        nE = register("entity.wolf.whine");
        nF = register("block.wooden_door.close");
        nG = register("block.wooden_door.open");
        nH = register("block.wooden_trapdoor.close");
        nI = register("block.wooden_trapdoor.open");
        nJ = register("block.wood.break");
        nK = register("block.wooden_button.click_off");
        nL = register("block.wooden_button.click_on");
        nM = register("block.wood.fall");
        nN = register("block.wood.hit");
        nO = register("block.wood.place");
        nP = register("block.wooden_pressure_plate.click_off");
        nQ = register("block.wooden_pressure_plate.click_on");
        nR = register("block.wood.step");
        nS = register("entity.zombie.ambient");
        nT = register("entity.zombie.attack_wooden_door");
        nU = register("entity.zombie.attack_iron_door");
        nV = register("entity.zombie.break_wooden_door");
        nW = register("entity.zombie.converted_to_drowned");
        nX = register("entity.zombie.death");
        nY = register("entity.zombie.destroy_egg");
        nZ = register("entity.zombie_horse.ambient");
        oa = register("entity.zombie_horse.death");
        ob = register("entity.zombie_horse.hurt");
        oc = register("entity.zombie.hurt");
        od = register("entity.zombie.infect");
        oe = register("entity.zombie_pigman.ambient");
        of = register("entity.zombie_pigman.angry");
        og = register("entity.zombie_pigman.death");
        oh = register("entity.zombie_pigman.hurt");
        oi = register("entity.zombie.step");
        oj = register("entity.zombie_villager.ambient");
        ok = register("entity.zombie_villager.converted");
        ol = register("entity.zombie_villager.cure");
        om = register("entity.zombie_villager.death");
        on = register("entity.zombie_villager.hurt");
        oo = register("entity.zombie_villager.step");
    }
}
